In [10]:
import torch

creating tensors:

- Scaler tensor -> - dimention tensor
- 1D tensor -> vector
- 2D tensor -> matrix
- 3D tensor -> volume
- nD tensor -> n dimention tensor

In [11]:
#Tensor attributes:
scaler=torch.tensor(42)
print(scaler) # tensor(42)
print(f"The dimention is: {scaler.dim()}")  # dim() return the number of dimention
print(f"The shape is: {scaler.shape}")  # shape return the shape of tensor
print(f"The size is: {scaler.size()}")  # size() return the size of tensor
print(f"The value is: {scaler.item()}")  # item() return the value of tensor

tensor(42)
The dimention is: 0
The shape is: torch.Size([])
The size is: torch.Size([])
The value is: 42


In [17]:
# 1-dimensional tensor
vector=torch.tensor([1,2,3,4])
print(vector)  # tensor([1, 2, 3, 4])
print(f"The dimention is: {vector.ndim}")  # ndim return the number of dimention
print(f"The shape is: {vector.shape}")  # shape return the shape of tensor
print(f"The size is: {vector.size()}")  # size() return the size of tensor
print(f"The value is: {vector[0].item()}")  # item() return the value of tensor

tensor([1, 2, 3, 4])
The dimention is: 1
The shape is: torch.Size([4])
The size is: torch.Size([4])
The value is: 1


In [ ]:
# matrix: 2-dimensional tensor

matrix=torch.tensor([[1,2,3],[4,5,6]])
print(matrix)  # tensor([[1, 2, 3], [4, 5, 6]])
print(f"The dimention is: {matrix.ndim}")  # ndim return the number of dimention
print(f"The shape is: {matrix.shape}")  # shape return the shape of tensor
print(f"The size is: {matrix.size()}")  # size() return the size of tensor
print(f"The value is: {matrix[0,0].item()}")  # item() return the value of tensor

tensor([[1, 2, 3],
        [4, 5, 6]])
The dimention is: 2
The shape is: torch.Size([2, 3])
The size is: torch.Size([2, 3])
The value is: 1


In [ ]:
# 3d tensor
tensor_3d=torch.tensor([[[1,2,3],[4,5,6]],
                        [[7,8,9],[10,11,12]],
                        [[13,14,15],[16,17,18]]])
print(tensor_3d)  # tensor([[[ 1,  2,  3],
                  #          [ 4,  5,  6]],
                  #         [[ 7,  8,  9],
                  #          [10, 11, 12]],
                  #         [[13, 14, 15],
                  #          [16, 17, 18]]])
print(f"\n\nThe dimention is: {tensor_3d.ndim}")  # ndim return the number of dimention
print(f"The shape is: {tensor_3d.shape}")  # shape return the shape of tensor
print(f"The size is: {tensor_3d.size()}")  # size() return the size of tensor
print(f"The value is: {tensor_3d[0,0,0].item()}")  # item() return the value of tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
The dimention is: 3
The shape is: torch.Size([3, 2, 3])
The size is: torch.Size([3, 2, 3])
The value is: 1


In [22]:
# GPU accleration
vector=torch.tensor([1,2,3,4])
print(vector)
print(f"Device: {vector.device}")  # default device is CPU

if torch.cuda.is_available():
    tensor_on_gpu = vector.to("cuda")
    print(tensor_on_gpu)
    print(f"Device: {tensor_on_gpu.device}")
else:
    print("GPU not available.")

tensor([1, 2, 3, 4])
Device: cpu
GPU not available.


In [26]:
# tensor properties
print(f"Datatype of vector: {vector.dtype}")  # default datatype is int64
print(f"Datatype of matrix: {matrix.dtype}")  # default datatype is int64

float_vector=vector.type(torch.FloatTensor)
print(float_vector)
print(f"Datatype of float_vector: {float_vector.dtype}")  # datatype is float32

Datatype of vector: torch.int64
Datatype of matrix: torch.int64
tensor([1., 2., 3., 4.])
Datatype of float_vector: torch.float32


In [30]:
print(f"The matrix exists on device: {matrix.device}")
matrix_on_gpu = matrix.to("cuda") if torch.cuda.is_available() else matrix
print(f"The matrix exists on device: {matrix_on_gpu.device}")
print(matrix.is_cuda)  # return True if the tensor is on GPU else False

The matrix exists on device: cpu
The matrix exists on device: cpu
False


In [33]:
print(f"Number of elements in the matrix: {matrix.numel()}") # numel() return the number of elements in the tensor
print(f"Size {matrix.size()}")

Number of elements in the matrix: 6
Size torch.Size([2, 3])
