In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu126
False


In [3]:
# Accessing elements in a tensor
tensor=torch.tensor([[10,20,30], [40,50,60], [70,80,90]])
print(tensor.ndim)
print(tensor.shape)

2
torch.Size([3, 3])


In [4]:
print("Element at row 0, column 1:", tensor[0,1])
print("Element at row 0, column 1:", tensor[0][1])

Element at row 0, column 1: tensor(20)
Element at row 0, column 1: tensor(20)


In [5]:
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [6]:
print(tensor[0]) # first row
print(tensor[:,0]) # first column
print(tensor[:,1]) # second column
print(tensor[0:2, 0:2]) # first two rows and first two columns

tensor([10, 20, 30])
tensor([10, 40, 70])
tensor([20, 50, 80])
tensor([[10, 20],
        [40, 50]])


In [7]:
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [8]:
# Slicing operation
print(tensor[1:3, 1:3]) # last two rows and last two columns

tensor([[50, 60],
        [80, 90]])


In [9]:
tensor

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [10]:
print(tensor[0:3,0:2])
print(tensor[1,1])
print(tensor[1:2, 1:])

tensor([[10, 20],
        [40, 50],
        [70, 80]])
tensor(50)
tensor([[50, 60]])


In [11]:
print(tensor)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [12]:
# Fancy indexing
# (0,1) -> 20
# (2,2) -> 90

print(tensor[[0,2], [1,2]])
print(tensor[[0,2], [0,2]])

tensor([20, 90])
tensor([10, 90])


In [13]:
# boolean indexing
mask=tensor>50
print(mask)
print(tensor[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [14]:
# changing values in a tensor
tensor[0,0]=999
print(tensor)

tensor([[999,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]])


In [15]:
tensor[:,0]=torch.tensor([100,200,300])
print(tensor)

tensor([[100,  20,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [16]:
indices=torch.tensor([0,2])
print(torch.index_select(tensor, dim=0, index=indices))  # select rows with indices 0 and 2
print(torch.index_select(tensor, dim=1, index=indices))  # select rows with indices 0 and 2

tensor([[100,  20,  30],
        [300,  80,  90]])
tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [17]:
# using tensor with steps
print(tensor[:, ::2]) # all rows, every second column

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [18]:
# print(tensor[::-1, :]) # reverse rows, does not work
print(torch.flip(tensor, dims=[0]))  # flip rows
print(torch.flip(tensor, dims=[1]))  # flip columns
print(torch.flip(tensor, dims=[0,1]))  # flip both rows and columns

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  20,  30]])
tensor([[ 30,  20, 100],
        [ 60,  50, 200],
        [ 90,  80, 300]])
tensor([[ 90,  80, 300],
        [ 60,  50, 200],
        [ 30,  20, 100]])
