In [1]:
import torch
# Comparing tensor[,] vs tensor[][]
tensor = torch.tensor([[10,20,30], [40,50,60], [70,80,90]])
print("Original tensor:")
print(tensor)
print("\n" + "="*50)

# Case 1: When tensor[][] works as expected
print("\n1. Getting a single element:")
print(f"tensor[1][2] = {tensor[1][2]}")  # Gets element at row 1, col 2
print(f"tensor[1,2] = {tensor[1,2]}")    # Same result

print("\n2. Getting a single row, then slicing columns:")
print(f"tensor[1][:2] = {tensor[1][:2]}")  # Row 1, first 2 columns
print(f"tensor[1,:2] = {tensor[1,:2]}")    # Same result

# Case 2: When tensor[][] gives unexpected results
print("\n3. Trying to get submatrix - DIFFERENT RESULTS:")
print(f"tensor[0:2][0:2] = \n{tensor[0:2][0:2]}")  # First 2 rows, then first 2 of those rows
print(f"tensor[0:2,0:2] = \n{tensor[0:2,0:2]}")    # First 2 rows AND first 2 columns

print("\n4. Why the difference?")
print(f"tensor[0:2] gives us:\n{tensor[0:2]}")
print(f"Then [0:2] on that result gives first 2 rows of the 2x3 matrix above")
print(f"But tensor[0:2,0:2] selects rows AND columns simultaneously")

Original tensor:
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


1. Getting a single element:
tensor[1][2] = 60
tensor[1,2] = 60

2. Getting a single row, then slicing columns:
tensor[1][:2] = tensor([40, 50])
tensor[1,:2] = tensor([40, 50])

3. Trying to get submatrix - DIFFERENT RESULTS:
tensor[0:2][0:2] = 
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor[0:2,0:2] = 
tensor([[10, 20],
        [40, 50]])

4. Why the difference?
tensor[0:2] gives us:
tensor([[10, 20, 30],
        [40, 50, 60]])
Then [0:2] on that result gives first 2 rows of the 2x3 matrix above
But tensor[0:2,0:2] selects rows AND columns simultaneously
