In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu126
False


# datatypes for tensors
 - float --> for most deep learning tasks --> float32, float64, float16
 - integer --> for categorical data and indices --> int8, int32, int64
 - boolean --> used to create masks or logical operations
 - complex --> advanced computation --> complex64, complex128


#### memory consumption: 
- float64 >> float32 >> float16

#### computation: 
- lower precision will be faster on gpus
 
 
#### numerical precision: 
- float64 is more precise than float32

In [4]:
# datatypes for tensors
default_tensor_int=torch.tensor([1,2,3])
print(default_tensor_int.dtype)

default_tensor_float=torch.tensor([1.0,2.0,3.0])
print(default_tensor_float.dtype)

torch.int64
torch.float32


In [7]:
float_tensor=torch.tensor([1.0,2.0,3.0], dtype=torch.float16)
print(float_tensor)
print(float_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [8]:
int_tensor=torch.tensor([1,2,3], dtype=torch.int16)
print(int_tensor)
print(int_tensor.dtype)

tensor([1, 2, 3], dtype=torch.int16)
torch.int16


In [9]:
int_tensor_2=torch.tensor([1,2,3])
print(int_tensor_2)
print(int_tensor_2.dtype) 

tensor([1, 2, 3])
torch.int64


In [11]:
boolean_tensor=torch.tensor([True,False,True], dtype=torch.bool)
print(boolean_tensor)
print(boolean_tensor.dtype)

tensor([ True, False,  True])
torch.bool


In [15]:
# convert from one datatype to another
float_tensor_1=torch.tensor([1.0,2.0,3.0])
print(float_tensor_1.dtype)
print(float_tensor_1)

float_tensor_converted_to_int64=float_tensor_1.to(torch.int64)
print(float_tensor_converted_to_int64)
print(float_tensor_converted_to_int64.dtype)

torch.float32
tensor([1., 2., 3.])
tensor([1, 2, 3])
torch.int64


In [18]:
new_int_tensor=torch.tensor([0,1,2,0,-1])
converted_to_boolean_tensor=new_int_tensor.to(torch.bool)
print(new_int_tensor)
print(converted_to_boolean_tensor)
print(new_int_tensor.dtype)
print(converted_to_boolean_tensor.dtype)

tensor([ 0,  1,  2,  0, -1])
tensor([False,  True,  True, False,  True])
torch.int64
torch.bool


- returns the size of an element in bytes -->  tensor_name.element_size()
- returns the total number of elements in the tensor --> tensor_name.numel() 
- gives the total size of the tensor in bytes --> tensor_name.element_size() * tensor_name.numel() 
- gives the total size of the tensor in -megabytes --> tensor_name.nelement_size() * tensor_name.numel() / (1024 ** 2) 
- gives the total size of the tensor in megabytes --> tensor_name.element_size() * tensor_name.numel() / (1024 ** 2) 
- gives the total size of the tensor in gigabytes --> tensor_name.element_size() * tensor_name.numel() / (1024 ** 3) 

In [31]:
# impact of datatype on memory
float_32_tensor=torch.ones(1000, dtype=torch.float32)
float_64_tensor=torch.ones(1000, dtype=torch.float64)
print(float_32_tensor.element_size())
print(float_64_tensor.element_size())


print(f"Total elements --> {float_32_tensor.nelement()}")
print(f"Size of element --> {float_32_tensor.element_size()}")


print(f"memory for float 32 tensor: {float_32_tensor.nelement() * float_32_tensor.element_size()} bytes")
print(f"memory for float 64 tensor: {float_64_tensor.nelement() * float_64_tensor.element_size()} bytes")

4
8
Total elements --> 1000
Size of element --> 4
memory for float 32 tensor: 4000 bytes
memory for float 64 tensor: 8000 bytes


In [43]:
print(float_32_tensor.element_size())
print(float_32_tensor.nelement())
print(f"Memory --> {float_32_tensor.nelement() * float_32_tensor.element_size()} bytes")

4
1000
Memory --> 4000 bytes


In [44]:
print(float_64_tensor.element_size())
print(float_64_tensor.nelement())
print(f"Memory --> {float_64_tensor.nelement() * float_64_tensor.element_size()} bytes")

8
1000
Memory --> 8000 bytes


## float datatype use case
- float 16 --> mixed precision training (faster to train on modern hardware, less memory, but less accurate)
- float 32 --> default for most deep learning neutal network models
- float 64 --> default for high precision scientific computing


## int datatype use case
- int8 and int16 --> used for reducing memory 
- int32 --> general purpose computation
- int64 --> used for tensor indices


## bool datatype use case
- bool --> mask and logical operation


## complex datatype use case
- complex64 and complex128 --> advanced computation