# Manipulating tensors
- reshaping
- slicing
- joining or splitting 
- transposing and permuting dimension
- cloning and detaching

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu126
False


In [3]:
# reshaping tensors --> reshape and view
original_tensor=torch.arange(12) # 1D tensor with values from 0 to 11
print(f"Original tensor: \n{original_tensor}")

Original tensor: 
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [5]:
print(original_tensor.ndim)
print(original_tensor.shape)
print(original_tensor.nelement())
print(original_tensor.device)

1
torch.Size([12])
12
cpu


In [6]:
# changing the dimention of a tensor
reshaped_tensor=original_tensor.reshape(3,4) # reshape to 3 rows and 4 columns
print(f"Reshaped tensor: \n{reshaped_tensor}")
print(reshaped_tensor.ndim)
print(reshaped_tensor.shape)
print(reshaped_tensor.nelement())
print(reshaped_tensor.device)

Reshaped tensor: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2
torch.Size([3, 4])
12
cpu


In [7]:
reshaped_tensor_1=original_tensor.reshape(2,6) # reshape to 2 rows and 6 columns
print(f"Reshaped tensor: \n{reshaped_tensor_1}")
print(reshaped_tensor_1.ndim)
print(reshaped_tensor_1.shape)
print(reshaped_tensor_1.nelement())
print(reshaped_tensor_1.device)

Reshaped tensor: 
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2
torch.Size([2, 6])
12
cpu


In [8]:
# view operation --> returns a new tensor with the same data as the original tensor but with a different shape, requires the original tensor to be contiguous in memory

viewed_tensor=original_tensor.view(3,4) # view to 3 rows and 4 columns
print(f"Viewed tensor: \n{viewed_tensor}")
print(viewed_tensor.ndim)
print(viewed_tensor.shape)
print(viewed_tensor.nelement())
print(viewed_tensor.device)

Viewed tensor: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2
torch.Size([3, 4])
12
cpu


In [12]:
#  -1--> infer the size of the dimension based on the number of elements in the original tensor and the specified dimensions
reshaped_tensor_2=original_tensor.reshape(4,-1) # reshape to 4 rows and infer the number of columns
print(f"Reshaped tensor with -1: \n{reshaped_tensor_2}")
print(reshaped_tensor_2.ndim)
print(reshaped_tensor_2.shape)
print(reshaped_tensor_2.nelement())
print(reshaped_tensor_2.device)

Reshaped tensor with -1: 
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
2
torch.Size([4, 3])
12
cpu


In [13]:
flattened_tensor=original_tensor.reshape(-1) # flatten the tensor to 1D
print(f"Flattened tensor: \n{flattened_tensor}")
print(flattened_tensor.ndim)
print(flattened_tensor.shape)
print(flattened_tensor.nelement())
print(flattened_tensor.device)

Flattened tensor: 
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
1
torch.Size([12])
12
cpu


In [15]:
# check wether the original tensor is contiguous in memory
# reshaping a tensor with reshape does not change the memory layout of the original tensor, but view requires the original tensor to be contiguous in memory, view does not work if the original tensor is not contiguous in memory, but reshape works regardless of the memory layout of the original tensor
print(original_tensor.is_contiguous())

True


#### Slicing operation
- we extract specific portions of tensors

In [16]:
tensor_a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.is_contiguous())
print(tensor_a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
True
2


In [23]:
print(tensor_a[0])
print(tensor_a[:,0])
print(tensor_a[:,2])

tensor([1, 2, 3])
tensor([1, 4, 7])
tensor([3, 6, 9])


In [24]:
print(tensor_a.ndim)
print(tensor_a.shape)
print(tensor_a.element_size())
print(tensor_a.nelement())
print(tensor_a.device)

2
torch.Size([3, 3])
8
9
cpu


#### Joining tensors
- torch.cat() ---> merges the tensors along an existing dimention

In [25]:
tensor_1=torch.tensor([[1,2],[3,4]])
tensor_2=torch.tensor([[5,6],[7,8]])

print(tensor_1)
print(tensor_2)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [26]:
concat_tensor_rows=torch.cat((tensor_1,tensor_2),dim=0) # concatenate along the rows (dim=0 --> vertical concatenation)
concat_tensor_cols=torch.cat((tensor_1,tensor_2),dim=1) # concatenate along the columns (dim=1 --> horizontal concatenation)

In [30]:
print("Merged along rows:\n"+str(concat_tensor_rows))
print("\n\nMerged along columns:\n"+str(concat_tensor_cols))

Merged along rows:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


Merged along columns:
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [31]:
# stack --> creates a new dimension which increases the tensor's rank by 1, stack requires the input tensors to have the same shape, stack concatenates the input tensors along a new dimension, the new dimension is specified by the dim argument, if dim=0 --> stack along the first dimension, if dim=1 --> stack along the second dimension, and so on


stack_tensor_rows=torch.stack((tensor_1,tensor_2),dim=0)
stack_tensor_cols=torch.stack((tensor_1,tensor_2),dim=1)

In [32]:
print(tensor_1.shape)
print(tensor_2.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [33]:
print(stack_tensor_rows.shape)
print(stack_tensor_cols.shape)

torch.Size([2, 2, 2])
torch.Size([2, 2, 2])


In [35]:
print(tensor_1)
print(tensor_2)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])


In [34]:
print(stack_tensor_rows)
print(stack_tensor_cols)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


#### Splitting tensors
- torch.chunk()  ---> divides the tensor into equal sized chunks
- torch.spilit() ---> allows uneven splitting based on size of the tensor

In [47]:
# torch.chunk()  --> splits a tensor into a specified number of chunks along a specified dimension, the number of chunks is specified by the chunks argument, the dimension along which to split the tensor is specified by the dim argument, if dim=0 --> split along the first dimension, if dim=1 --> split along the second dimension, and so on, the last chunk may be smaller than the others if the tensor cannot be evenly divided by the number of chunks


orig_tensor=torch.arange(12)
chunks=torch.chunk(orig_tensor,4, dim=0) # split the tensor into 4 chunks along the first dimension (dim=0 by default)
print(chunks)


for chunk in chunks:
    print(chunk)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [52]:
# torch.split() --> splits a tensor into chunks of a specified size along a specified dimension, the size of each chunk is specified by the split_size argument, the dimension along which to split the tensor is specified by the dim argument, if dim=0 --> split along the first dimension, if dim=1 --> split along the second dimension, and so on, the last chunk may be smaller than the others if the tensor cannot be evenly divided by the split size


original_tensor=torch.arange(10)
split_tensor=torch.split(original_tensor, 8, dim=0) # split the tensor into chunks of size 8 along the first dimension (dim=0 by default)
print(split_tensor)

for split in split_tensor:
    print(split)

(tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([8, 9]))
tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([8, 9])


#### Transposing and permuting
- transpose():  swaps the two dimensions, (mxn) --> nxm
- permute(): rearranges all dimensions in the specified order

In [53]:
original_tensor=torch.arange(24).reshape(2,3,4)
print(original_tensor)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [59]:
# transpose --> permutes the dimensions of a tensor, the dimensions to be permuted are specified by the dim0 and dim1 arguments, if dim0=0 and dim1=1 --> transpose the first and second dimensions, if dim0=1 and dim1=2 --> transpose the second and third dimensions, and so on

transposed_tensor=original_tensor.transpose(0,1) # transpose the first and second dimensions


print(original_tensor)
print("\n\n")
print(transposed_tensor)
print("\n\n")

print(original_tensor.shape)
print(transposed_tensor.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])



tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])



torch.Size([2, 3, 4])
torch.Size([3, 2, 4])


In [63]:
# permute --> permutes the dimensions of a tensor, the dimensions to be permuted are specified by the dims argument, which is a tuple of the new order of the dimensions, for example, if dims=(1,0,2) --> permute the first dimension to the second position, the second dimension to the first position, and keep the third dimension in the same position


# tensor dimensions:    2,3,4
# index of dimensions:  0,1,2

# at index 0 --> 2
# at index 1 --> 3
# at index 2 --> 4

# now we want to permute the dimensions to be in the order of 1,0,2 --> the first dimension (2) will be moved to the second position, the second dimension (3) will be moved to the first position, and the third dimension (4) will remain in the same position

# after permuting the dimensions, the new order of the dimensions will be 3,2,4 --> the first dimension will be 3, the second dimension will be 2, and the third dimension will be 4


original_tensor=torch.arange(24).reshape(2,3,4)
print(original_tensor)
print("\n\n")
permuted_tensor=original_tensor.permute(1,0,2) # permute the first dimension to the second position, the second dimension to the first position, and keep the third dimension in the same position
print(permuted_tensor)
print("\n\n")
print(original_tensor.shape)
print(permuted_tensor.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])



tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])



torch.Size([2, 3, 4])
torch.Size([3, 2, 4])


#### cloning and detaching tensors 

- cloning a tensor creates a copy of the original tensor with the same data and the same computational graph, 
 
- detaching a tensor creates a new tensor that shares the same data as the original tensor but does not require gradients and is not part of the computational graph

In [68]:
import copy
a=[1,2,3]
b=copy.deepcopy(a)
print(a)
print(b)

print(id(a))
print(id(b))

print(a == b)
print(a is b)

[1, 2, 3]
[1, 2, 3]
134998921451392
134998921452672
True
False


In [69]:
tensor=torch.ones(3,3, requires_grad=True) # part of computation graph, so it will be updated during backpropagation, and it will contribute to the gradients of the original tensor
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [73]:
cloned_tensor=tensor.clone() # clone creates a copy of the tensor with the same data and the same requires_grad property, but it does not share the same memory as the original tensor, so changes to the cloned tensor will not affect the original tensor, and vice versa. Part of computation graph, so it will be updated during backpropagation, and it will contribute to the gradients of the original tensor

print(cloned_tensor)
print(cloned_tensor.requires_grad)


tensor.detach_() # detach creates a new tensor that shares the same data as the original tensor but does not require gradients, changes to the detached tensor will affect the original tensor, but changes to the original tensor will not affect the detached tensor, detached from the computation graph, so it will not be updated during backpropagation, and it will not contribute to the gradients of the original tensor, but storage is shared between the original tensor and the detached tensor, so changes to the data of the detached tensor will affect the original tensor, and changes to the data of the original tensor will affect the detached tensor

print(tensor)
print(tensor.requires_grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
False
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
False
