### Matrix Aggregation

In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu126
False


In [4]:
matrix=torch.tensor([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.]], device='cpu')
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [12]:
print(matrix.sum())
print(matrix.min())
print(matrix.max())
print(matrix.mean())
print(matrix.std())
print(matrix.median())

tensor(45.)
tensor(1.)
tensor(9.)
tensor(5.)
tensor(2.7386)
tensor(5.)


In [15]:
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


* matrix.mean(0) --> mean along rows, but in reality, it calculates along columns 
* matrix.mean(1) --> mean along cols, but in reality, it calculates along rows 

In [14]:
print(matrix.mean(0)) # mean along the columns
print(matrix.mean(1)) # mean along the rows

tensor([4., 5., 6.])
tensor([2., 5., 8.])


In [16]:
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [21]:
print(matrix.max(dim=0)) # max along rows, but actually across columns

torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))


In [22]:
print(matrix.max(dim=1)) # max along cols, but actually across rows

torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [23]:
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [25]:
cumsum_0=matrix.cumsum(dim=0) # cumulative sum along rows --> working on cols
cumsum_1=matrix.cumsum(dim=1) # cumulative sum along cols --> working on rows
print(cumsum_0)
print(cumsum_1)

tensor([[ 1.,  2.,  3.],
        [ 5.,  7.,  9.],
        [12., 15., 18.]])
tensor([[ 1.,  3.,  6.],
        [ 4.,  9., 15.],
        [ 7., 15., 24.]])


In [27]:
print(matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [26]:
cumprod_0=matrix.cumprod(dim=0) # cumulative product along rows --> working on cols
cumprod_1=matrix.cumprod(dim=1) # cumulative product along cols --> working on rows
print(cumprod_0)
print(cumprod_1)

tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])
tensor([[  1.,   2.,   6.],
        [  4.,  20., 120.],
        [  7.,  56., 504.]])


In [28]:
matrix

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [29]:
# Advance aggregation
masked_matrix_sum=matrix[matrix>5].sum()
print(masked_matrix_sum)

tensor(30.)


In [40]:
print(matrix.nonzero())
print(matrix.count_nonzero())
print(matrix.nonzero().size()) # number of non-zero elements in the matrix
print(matrix.nonzero().size(0)) 
print(matrix.nonzero().size(1)) 

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2],
        [2, 0],
        [2, 1],
        [2, 2]])
tensor(9)
torch.Size([9, 2])
9
2


##### Normalized matrix

In [41]:
print(matrix)
max_v=matrix.max()
min_v=matrix.min()
normalized_matrix=(matrix-min_v)/(max_v-min_v)
print(normalized_matrix)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[0.0000, 0.1250, 0.2500],
        [0.3750, 0.5000, 0.6250],
        [0.7500, 0.8750, 1.0000]])
