### View and Reshape

- both are used to change the shape of tensors
- transform the tensor into a new shape, keeping the data consistent

* view ---> works if the tensor is stored contiguously in memory
* reshape ---> can handle the non contiguous tensors is stored in the memory


#### Contiguous meaning:
- The data remains same in the memory, but the access pattern changes. Contiguous data is strict in access, has advantage in performance


##### Problem with non contiguous data:
- Pytorch, now have to perform indexing, and it is computationally expensive


##### performance: Contiguous Data >>> Non Contiguous Data 

In [16]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu126
False


In [17]:
original_tensor=torch.tensor([[1,2,3],[4,5,6]])
print(original_tensor.is_contiguous())

True


In [18]:
print(original_tensor.T)
print(original_tensor.T.is_contiguous())

tensor([[1, 4],
        [2, 5],
        [3, 6]])
False


- We can only use ****view**** when we are confident about the tensor contiguity, and need efficient operation. Only works with contiguous data.
- We can only use ****reshape**** when we are not-confident about the tensor contiguity, and need more robust and flexible operation. Reshape works with both contiguous and non contiguous data. When the data is non contiguous, reshape will create a copy and that copy is contiguous in nature. In case of contiguous data, no copy will be created.

In [19]:
tensor=torch.arange(12)
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [20]:
reshaped_tensor_view=tensor.view(2,6)
reshaped_tensor_reshaped=tensor.reshape(2,6)
print(reshaped_tensor_view)
print(reshaped_tensor_reshaped)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [21]:
print(reshaped_tensor_view.shape)
print(reshaped_tensor_reshaped.shape)

torch.Size([2, 6])
torch.Size([2, 6])


In [22]:
print(tensor.is_contiguous())

True


In [23]:
inferred_shape_1=tensor.view(3,-1)

print(inferred_shape_1)
print(inferred_shape_1.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [24]:
inferred_shape_2=tensor.reshape(3,-1)
print(inferred_shape_2)
print(inferred_shape_2.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [25]:
tensor_3d=torch.arange(24).reshape(2,3,4)
print(tensor_3d)
print(tensor_3d.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])


In [27]:
flattened=tensor_3d.view(-1)
print(flattened)
print(flattened.shape)
print(flattened.is_contiguous())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
torch.Size([24])
True


In [28]:
tensor_2d=torch.arange(24).reshape(12,2)
transpose_tensor=tensor_2d.t()
print(transpose_tensor)
print(transpose_tensor.shape)
print(transpose_tensor.is_contiguous())

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])
torch.Size([2, 12])
False


In [31]:
# error=transpose_tensor.view(6,4)   # error because the tensor is not contiguous
no_error=transpose_tensor.reshape(6,4)
print(no_error)
print(no_error.shape)


tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])


In [32]:
contiguous_tensor=transpose_tensor.contiguous()
no_error=contiguous_tensor.view(6,4)   # no error because the tensor is now contiguous
print(no_error)
print(no_error.shape)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
torch.Size([6, 4])
