In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cu126
False


In [2]:
tensor1=torch.tensor([1,2,3])
tensor2=torch.tensor([4,5,6])
print(tensor1.ndim, tensor1.shape)
print(tensor2.ndim, tensor2.shape)

1 torch.Size([3])
1 torch.Size([3])


In [3]:
print(tensor1)
print(tensor2)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [4]:
stacked_tensor_0=torch.stack((tensor1, tensor2), dim=0)
stacked_tensor_1=torch.stack((tensor1, tensor2), dim=1)

In [5]:
print(stacked_tensor_0)
print(stacked_tensor_1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [6]:
print(stacked_tensor_0.ndim,stacked_tensor_0.shape)
print(stacked_tensor_1.ndim,stacked_tensor_1.shape)

2 torch.Size([2, 3])
2 torch.Size([3, 2])


In [7]:
tensor3=torch.tensor([7,8,9])
stacked_tensor_2=torch.stack((tensor1, tensor2, tensor3), dim=0)
stacked_tensor_3=torch.stack((tensor1, tensor2, tensor3), dim=1)
print(stacked_tensor_2)
print(stacked_tensor_3)
print(stacked_tensor_2.ndim,stacked_tensor_2.shape)
print(stacked_tensor_3.ndim,stacked_tensor_3.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
2 torch.Size([3, 3])
2 torch.Size([3, 3])


In [8]:
tensor_2d_1=torch.tensor([[1,2,3],
                          [4,5,6],
                          [7,8,9]])
tensor_2d_2=torch.tensor([[10,11,12],
                          [13,14,15],
                          [16,17,18]])
stacked_tensor_4=torch.stack((tensor_2d_1, tensor_2d_2), dim=0)
stacked_tensor_5=torch.stack((tensor_2d_1, tensor_2d_2), dim=1)
stacked_tensor_6=torch.stack((tensor_2d_1, tensor_2d_2), dim=2)
print(stacked_tensor_4)
print(stacked_tensor_5)
print(stacked_tensor_6)
print(stacked_tensor_4.ndim,stacked_tensor_4.shape)
print(stacked_tensor_5.ndim,stacked_tensor_5.shape)
print(stacked_tensor_6.ndim,stacked_tensor_6.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
tensor([[[ 1,  2,  3],
         [10, 11, 12]],

        [[ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [16, 17, 18]]])
tensor([[[ 1, 10],
         [ 2, 11],
         [ 3, 12]],

        [[ 4, 13],
         [ 5, 14],
         [ 6, 15]],

        [[ 7, 16],
         [ 8, 17],
         [ 9, 18]]])
3 torch.Size([2, 3, 3])
3 torch.Size([3, 2, 3])
3 torch.Size([3, 3, 2])


concatenation operation

In [10]:
tensor_1=torch.tensor([[1, 2],[3, 4]])
tensor_2=torch.tensor([[5, 6],[7, 8]])
concat_tensor_0=torch.cat((tensor_1, tensor_2), dim=0)
concat_tensor_1=torch.cat((tensor_1, tensor_2), dim=1)
print(concat_tensor_0)
print(concat_tensor_1)
print(concat_tensor_0.ndim, concat_tensor_0.shape)
print(concat_tensor_1.ndim, concat_tensor_1.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
2 torch.Size([4, 2])
2 torch.Size([2, 4])
